### PR TITLE
Add resources_prefix property to YorcServer node type

### PR DESCRIPTION
**Pull request by stefbenoist**
# Pull Request description

## Description of the change

Update YorcServer Component to add resources_prefix property
See https://github.com/ystia/yorc/pull/401

### CODE REVIEW

**Review by laurentganne — APPROVED** [review]
Looks good !

**Review by loicalbertin — COMMENTED** [review]
Changelog update is missing

**Comment by stebenoist** [comment]
Done

**Review by loicalbertin — APPROVED** [review]
LGTM :+1: :clap:

**Pull request merged**
