### PR TITLE
Switch to alien 3.0.0

### PR DESCRIPTION
**Pull request by loicalbertin**
# Pull Request description

### What I did

Switched to Alien 3.0 dependencies
Updated version to 3.0.0-SNAPSHOT

### Description for the changelog

* Ystia Forge components require now Alien4Cloud 3.0.0

### CODE REVIEW

**Review by laurentganne — APPROVED** [review]
Looks good

**Comment by loicalbertin** [comment]
Yeah but do you think we need to tag a release 2.2.1 first with your changes below?

* Add docker container property to set the shared memory size 
* Installation of Consul and Ansible fails on recent Centos for GCP images

**Comment by loicalbertin** [comment]
> Yeah but do you think we need to tag a release 2.2.1 first with your changes below?
> 
> * Add docker container property to set the shared memory size
> * Installation of Consul and Ansible fails on recent Centos for GCP images

Ok I back-ported those PRs on release/2.2 branch.

Now I think we should move Yorc CI to release/2.2 as long as we do not bootstrap on Alien 3.0

**Comment by loicalbertin** [comment]
> > Yeah but do you think we need to tag a release 2.2.1 first with your changes below?
> > 
> > * Add docker container property to set the shared memory size
> > * Installation of Consul and Ansible fails on recent Centos for GCP images
> 
> Ok I back-ported those PRs on release/2.2 branch.
> 
> Now I think we should move Yorc CI to release/2.2 as long as we do not bootstrap on Alien 3.0

This is now done so let's merge

**Pull request merged**
